name: CI
on:
  push:
    branches: []
  pull_request:
    branches: [main]

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
    -name: CheckPoint code 
    uses: action/setup-python@4
    with: 
      python_version: '3.11'

  -name: Install dependencies
